name: Gradle publish plugin

on:
  push:
    tags: [*]

jobs:
  test:
    uses: GufliOfficial/.github/.github/workflows/java-gradle-test.yml@main

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Publish package
      uses: gradle/gradle-build-action@v2
      with:
        arguments: |
          publishPlugins 
          -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} 
          -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}